### ISSUE TITLE
Not working with Meteor v0.9.1

### ISSUE THREAD

**Issue by manybothans** [sergeyt/meteor-typeahead#29]
Breaking from the new Blaze updates. Getting the following exception in Web Inspector:

```
Exception from Tracker afterFlush function: undefined is not a function
TypeError: undefined is not a function
    at resolve_template_function (http://localhost:3000/packages/sergeyt:typeahead.js?012115c55b6c6f1a318aa003d312b3437be5612d:1907:20)
    at resolve_datasets (http://localhost:3000/packages/sergeyt:typeahead.js?012115c55b6c6f1a318aa003d312b3437be5612d:1848:15)
    at Object.Meteor.typeahead (http://localhost:3000/packages/sergeyt:typeahead.js?012115c55b6c6f1a318aa003d312b3437be5612d:1776:17)
    at Template.searchBar.rendered (http://localhost:3000/client/views/includes/search.js?89a2fabf2f17abeef220aa87d87c9f33257adb80:7:12)
    at null.<anonymous> (http://localhost:3000/packages/blaze.js?5ec4e54b22ab2196bcc772669c0619f71666393e:2807:21)
    at http://localhost:3000/packages/blaze.js?5ec4e54b22ab2196bcc772669c0619f71666393e:1712:14
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?5ec4e54b22ab2196bcc772669c0619f71666393e:2017:12)
    at http://localhost:3000/packages/blaze.js?5ec4e54b22ab2196bcc772669c0619f71666393e:1711:15
    at Tracker.flush (http://localhost:3000/packages/tracker.js?192a05cc46b867dadbe8bf90dd961f6f8fd1574f:438:11)
```

Caused by this line:
https://github.com/sergeyt/meteor-typeahead/blob/master/index.js#L168
